export default [{
		"name":"cough",
		"type": "icon",
		"requiresAnswer": [],
		"questionText": "Do you have a cough?",
		"iconText": ["yes", "no"],
		"iconColors": ["fb-green","fb-cyan" ],
		"iconImages":["images/icons/prefer_cold.png", "images/icons/prefer_warmer.png"],
	},
	{
		"name":"cough-difference",
		"type": "icon",
		"requiresAnswer": [{"question":"cough", "value": 11}],
		"questionText": "Worse than normal cough?",
		"iconText": ["yes", "no", "same"],
		"iconColors": ["fb-green","fb-cyan", "fb-orange" ],
		"iconImages":["images/icons/prefer_cold.png", "images/icons/prefer_warmer.png", "images/icons/outdoor.png"],
	},
	{
		"name":"cough-severity",
		"type": "icon",
		"requiresAnswer": [{"question":"cough", "value": 11}],
		"questionText": "How bad is your cough?",
		"iconText": ["sever", "frequent", "light"],
		"iconColors": ["fb-green","fb-cyan", "fb-orange" ],
		"iconImages":["images/icons/prefer_cold.png", "images/icons/prefer_warmer.png", "images/icons/outdoor.png"],
	},
	{
		"name":"cough-progress",
		"type": "icon",
		"requiresAnswer": [{"question":"cough", "value": 11}],
		"questionText": "Is it getting worse?",
		"iconText": ["yes", "no", "same"],
		"iconColors": ["fb-green","fb-cyan", "fb-orange" ],
		"iconImages":["images/icons/prefer_cold.png", "images/icons/prefer_warmer.png", "images/icons/outdoor.png"],
	},
	{
		"name":"fever",
		"type": "icon",
		"requiresAnswer": [],
		"questionText": "Do you have a fever?",
		"iconText": ["yes", "no", "don't know"],
		"iconColors": ["fb-green","fb-cyan", "fb-orange" ],
		"iconImages":["images/icons/prefer_cold.png", "images/icons/prefer_warmer.png", "images/icons/outdoor.png"],
	},

];