export default [
	{
		name: "cough",
		type: "icon",
		requiresAnswer: [],
		questionText: "Do you have a cough?",
		questionSecondText: "",
		iconText: ["yes", "no"],
		iconColors: ["fb-red", "fb-green"],
		iconImages: [
			"images/icons/cough.png",
			"images/icons/okay.png",
		],
	},
	{
		name: "cough-difference",
		type: "icon",
		requiresAnswer: [{ question: "cough", value: 11 }],
		questionText: "Is it worse than ",
		questionSecondText: "your normal cough?",
		iconText: ["yes", "no", "same"],
		iconColors: ["fb-red", "fb-cyan", "fb-orange"],
		iconImages: [
			"images/icons/high_cough.png",
			"images/icons/low_cough.png",
			"images/icons/mod_cough.png",
		],
	},
	{
		name: "cough-severity",
		type: "icon",
		requiresAnswer: [{ question: "cough", value: 11 }],
		questionText: "How frequent is",
		questionSecondText: "your cough?",
		iconText: ["constantly", "moderately", "light"],
		iconColors: ["fb-red", "fb-orange", "fb-cyan"],
		iconImages: [
			"images/icons/freq3.png",
			"images/icons/freq2.png",
			"images/icons/freq1.png",
		],
	},
	{
		name: "cough-progress",
		type: "icon",
		requiresAnswer: [{ question: "cough", value: 11 }],
		questionText: "Is your cough",
		questionSecondText: "getting worse?",
		iconText: ["yes", "no", "same"],
		iconColors: ["fb-red", "fb-cyan", "fb-orange"],
		iconImages: [
			"images/icons/high_cough.png",
			"images/icons/low_cough.png",
			"images/icons/mod_cough.png",
		],
	},
	{
		name: "breathing",
		type: "icon",
		requiresAnswer: [],
		questionText: "Is it difficult to breath?",
		questionSecondText: "",
		iconText: ["yes", "no"],
		iconColors: ["fb-red", "fb-green"],
		iconImages: [
			"images/icons/breath_worse.png",
			"images/icons/breath_good.png",
		],
	},
	{
		name: "breathing-progress",
		type: "icon",
		requiresAnswer: [{ question: "breathing", value: 11 }],
		questionText: "Is your breathing",
		questionSecondText: "getting worse?",
		iconText: ["yes", "no", "same"],
		iconColors: ["fb-red", "fb-cyan", "fb-orange"],
		iconImages: [
			"images/icons/breath_worse.png",
			"images/icons/breath_good.png",
			"images/icons/breath_same.png",
		],
	},
	{
		name: "breathing-resting",
		type: "icon",
		requiresAnswer: [{ question: "breathing", value: 11 }],
		questionText: "Is it difficult to breath",
		questionSecondText: "while resting?",
		iconText: ["yes", "no"],
		iconColors: ["fb-red", "fb-green"],
		iconImages: [
			"images/icons/breath_worse.png",
			"images/icons/breath_good.png",
		],
	},
	{
		name: "breathing-concern",
		type: "icon",
		requiresAnswer: [{ question: "breathing", value: 11 }],
		questionText: "Are you concerned with",
		questionSecondText: "your breathing?",
		iconText: ["yes", "no"],
		iconColors: ["fb-orange", "fb-cyan"],
		iconImages: [
			"images/icons/worry.png",
			"images/icons/neutral.png",
		],
	},
	{
		name: "fever",
		type: "icon",
		requiresAnswer: [],
		questionText: "Do you have a fever?",
		questionSecondText: "",
		iconText: ["yes", "no", "don't know"],
		iconColors: ["fb-orange", "fb-cyan", "fb-indigo"],
		iconImages: [
			"images/icons/fever_high.png",
			"images/icons/fever_low.png",
			"images/icons/fever_unk.png",
		],
	},
	{
		name: "fever-concern",
		type: "icon",
		requiresAnswer: [{ question: "fever", value: 11 }],
		questionText: "Are you concerned",
		questionSecondText: "about your fever?",
		iconText: ["yes", "no"],
		iconColors: ["fb-orange", "fb-cyan"],
		iconImages: [
			"images/icons/worry.png",
			"images/icons/neutral.png",
		],
	},
	{
		name: "thermometer",
		type: "icon",
		requiresAnswer: [],
		questionText: "Do you have a",
		questionSecondText: "thermometer?",
		iconText: ["yes", "no"],
		iconColors: ["fb-green", "fb-red"],
		iconImages: [
			"images/icons/have_thermo.png",
			"images/icons/no_thermo.png",
		],
	},
	{
		name: "fever",
		type: "numerical",
		requiresAnswer: [{ question: "thermometer", value: 11 }],
		questionText: "TODO: Add numerical input",
		questionSecondText: "",
		iconText: ["yes", "no", "don't know"],
		iconColors: ["fb-orange", "fb-cyan", "fb-indigo"],
		iconImages: [
			"images/icons/fever_high.png",
			"images/icons/fever_no.png",
			"images/icons/fever_unk.png",
		],
	},
	{
		name: "lethargy",
		type: "icon",
		requiresAnswer: [],
		questionText: "Do you feel tired?",
		questionSecondText: "",
		iconText: ["yes", "no"],
		iconColors: ["fb-orange", "fb-cyan"],
		iconImages: [
			"images/icons/lethargy.png",
			"images/icons/no_lethargy.png",
		],
	},
	{
		name: "lethargy-severity",
		type: "icon",
		requiresAnswer: [{ question: "lethargy", value: 11 }],
		questionText: "How severe is your",
		questionSecondText: "tiredness",
		iconText: ["mild", "moderate", "bed-bound"],
		iconColors: ["fb-green", "fb-cyan", "fb-red"],
		iconImages: [
			"images/icons/no_lethargy.png",
			"images/icons/lethargy.png",
			"images/icons/bedrest.png",
		],
	},
];
